# Generated by Django 5.1.7 on 2025-03-23 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название города')),
            ],
            options={
                'verbose_name': 'Города',
                'verbose_name_plural': 'Город',
            },
        ),
        migrations.CreateModel(
            name='DeliveryBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Кузов')),
            ],
            options={
                'verbose_name': 'Кузов',
                'verbose_name_plural': 'Кузов',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, verbose_name='Стоимость доставки')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.city', verbose_name='Город доставки')),
                ('body_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.deliverybody', verbose_name='Тип кузова')),
            ],
            options={
                'verbose_name': 'Стоимость',
                'verbose_name_plural': 'Стоимость',
            },
        ),
    ]
