# Generated by Django 5.1.7 on 2025-03-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название короткого видео')),
                ('link', models.TextField(verbose_name='Ссылка на короткое видео')),
                ('preview', models.TextField(verbose_name='Превью короткого видео')),
                ('video_path', models.TextField(default='zero', null=True, verbose_name='Путь к видео')),
                ('video_id', models.CharField(max_length=100, null=True, verbose_name='Айди видео')),
                ('date_published', models.DateField(verbose_name='Дата публикации видео ролика')),
            ],
            options={
                'verbose_name': 'Короткое видео',
                'verbose_name_plural': 'Короткое видео',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название видео')),
                ('link', models.TextField(verbose_name='Ссылка на видео')),
                ('preview', models.TextField(verbose_name='Превью видео')),
                ('video_id', models.CharField(max_length=100, null=True, verbose_name='Айди видео')),
                ('date_published', models.DateField(verbose_name='Дата публикации видео ролика')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videos_url', models.TextField(verbose_name='Ссылка на канал')),
                ('shorts_url', models.TextField(verbose_name='Ссылка на плейлист с шортсами')),
                ('review_url', models.TextField(verbose_name='Ссылка на плейлист с отзывами')),
                ('videos_count', models.IntegerField(verbose_name='Количество выгружаемых видео')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Ютуб',
            },
        ),
    ]
