# Generated by Django 5.1.7 on 2025-04-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='preview_img',
            field=models.ImageField(blank=True, null=True, upload_to='video'),
        ),
    ]
