# Generated by Django 5.1.7 on 2025-04-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_video_preview_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='preview_img',
            field=models.ImageField(blank=True, null=True, upload_to='video', verbose_name='Фото превью видео'),
        ),
    ]
