# Generated by Django 5.1.7 on 2025-04-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_alter_video_preview_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название видео')),
                ('link', models.TextField(verbose_name='Ссылка на видео')),
                ('preview', models.TextField(verbose_name='Превью видео')),
                ('preview_img', models.ImageField(upload_to='video', verbose_name='Фото превью видео')),
                ('video_id', models.CharField(max_length=100, null=True, verbose_name='Айди видео')),
                ('date_published', models.DateField(verbose_name='Дата публикации видео ролика')),
            ],
            options={
                'verbose_name': 'Видео отзывы',
                'verbose_name_plural': 'Видео отзывы',
            },
        ),
        migrations.AddField(
            model_name='shortvideo',
            name='preview_img',
            field=models.ImageField(blank=True, null=True, upload_to='video', verbose_name='Превью видео'),
        ),
    ]
