# Generated by Django 5.1.7 on 2025-04-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИ члена команды')),
                ('position', models.CharField(max_length=50, verbose_name='Должность')),
                ('image_user', models.ImageField(upload_to='users')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команда',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='MainBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_clients', models.CharField(max_length=50, verbose_name='Рейтинг клиентов')),
                ('year', models.IntegerField(verbose_name='Лет на рынке')),
                ('cnt_car', models.CharField(max_length=100, verbose_name='Авто привезли')),
                ('min_day_delivery', models.CharField(max_length=100, verbose_name='Минимальный срок доставки')),
            ],
            options={
                'verbose_name': 'Главный экран',
                'verbose_name_plural': 'Главный экран',
            },
        ),
        migrations.CreateModel(
            name='StagesOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Этапы работы',
                'verbose_name_plural': 'Этапы работы',
            },
        ),
    ]
